version: "3.4"
services:
  database-service:
    env_file: ./docker/credenciais/database/.env
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: container-database
    ports:
      - "3306:3306"
    volumes:
      - ./database/data/mysql:/var/lib/mysql
      - ./database/dump:/docker-entrypoint-initdb.d
    networks:
      - estudo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 20

  app-service:
    links:
      - "database-service"
    depends_on:
      - "database-service"
    user: root
    env_file: ./docker/credenciais/app/.env
    build: ./app
    image: vinnyfs89/web-server:0.0.0
    container_name: app-container
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/log/apache2:/var/log/apache2
    networks:
      - estudo_network

networks:
  estudo_network:
    name: estudo_network
    driver: bridge
